[[redirects]]
  from = "https://sqyy.opendatachina.org"
  to = "https://opendatachina.feishu.cn/wiki/space/7290440869055627267?ccm_open_type=lark_wiki_spaceLink&open_tab_from=wiki_home"
  status = 301
  force = true
